# Included tasks for FAS deployments (legacy)

- name: Installing required packages
  yum:                                                                                                             
    name: "{{ ipsilon_fas_packages }}"
    state: latest
  tags:
    - packages

- name: Initializing ipsilon if needed
  command: "ipsilon-server-install --admin-user admin --secure yes --openid yes --saml2 yes --openidc no --fas yes --database-url mysql://{{ ipsilon_db_user }}:{{ ipsilon_db_pass }}@localhost/ipsilon --hostname {{ ipsilon_httpd_hostname }}"
  args:
    creates: /etc/ipsilon/idp/ipsilon.conf
  no_log: True
  register: ipsilon_install
  tags:
    - init

  
