# Included tasks for FAS deployments (legacy)

- name: Installing required packages
  ansible.builtin.yum:
    name: "{{ ipsilon_fas_packages }}"
    state: latest
  tags:
    - packages

- name: Initializing ipsilon if needed
  ansible.builtin.command: "ipsilon-server-install --admin-user admin --secure yes --openid yes --saml2 yes --openidc no --fas yes --database-url mysql://{{ ipsilon_db_user }}:{{ ipsilon_db_pass }}@localhost/ipsilon --hostname {{ ipsilon_httpd_hostname }}"
  args:
    creates: /etc/ipsilon/idp/ipsilon.conf
  no_log: True
  register: ipsilon_install
  tags:
    - init

- name: Importing template for ipsilon DB
  ansible.builtin.template:
    src: ipsilon-db-cfg-fas.sql.j2
    dest: /etc/ipsilon/idp/ipsilon-db-cfg.sql
  register: ipsilon_db_cfg 

- name: Configuring ipsilon DB from template
  mysql_db:
    name: "{{ ipsilon_db_name }}"
    state: import
    target: /etc/ipsilon/idp/ipsilon-db-cfg.sql
  when: ipsilon_db_cfg is changed
  tags:
    - init

  
