# Defaults tasks for role ipsilon
- name: Importing specific distro variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"

- include_role:
    name: mysql
  tags:
    - db

- name: Creating mandatory (local) DB 
  include_role: 
    name: mysql
    tasks_from: db
  vars:
    mysql_db_user: "{{ ipsilon_db_user }}"
    mysql_db_pass: "{{ ipsilon_db_pass }}"
    mysql_db_name: "{{ item }}"
  with_items:
    - "{{ ipsilon_db_name }}"
    - "{{ ipsilon_db_name }}_static"
  tags:
    - db

- block:
    - name: Enabling EPEL for .el8 deps
      yum:
        name: epel-release
        state: installed
    # FIXME : waiting for ipsilon to be available but blocked by https://bugzilla.redhat.com/show_bug.cgi?id=1888195    
    - name: Workaround for ipsilon/lasso pkgs
      command: dnf copr enable -y arrfab/noggin
        
  when: ansible_distribution_major_version == '8'
  tags:
    - test

- include_tasks: ipa.yml
  when: ipsilon_ipa_auth
  tags:
    - ipa
    - init

- include_tasks: fas.yml
  when: ipsilon_fas_auth
  
- name: Importing template for ipsilon DB
  template:
    src: ipsilon-db-cfg.sql.j2
    dest: /etc/ipsilon/idp/ipsilon-db-cfg.sql
  register: ipsilon_db_cfg 
  when: ipsilon_install is changed
  tags:
    - init

- name: Configuring ipsilon DB from template
  mysql_db:
    name: "{{ ipsilon_db_name }}"
    state: import
    target: /etc/ipsilon/idp/ipsilon-db-cfg.sql
  when: ipsilon_db_cfg is changed
  tags:
    - init

- name: Ipsilon admins template
  template:
    src: ipsilon-admins.sql.j2
    dest: /etc/ipsilon/idp/ipsilon-admins.sql
  register: ipsilon_admins 
  tags:
    - init
    - admins

- name: Configuring ipsilon admins
  mysql_db:
    name: "{{ ipsilon_db_name }}"
    state: import
    target: /etc/ipsilon/idp/ipsilon-admins.sql
  when: ipsilon_admins is changed
  tags:
    - init
    - admins

- name: Configuring httpd
  import_role:
    name: httpd
  vars:
    httpd_tls: "{{ ipsilon_httpd_tls }}"

- name: Configuring httpd vhost
  template:
    src: 02_ipsilon_vhost.conf.j2
    dest: /etc/httpd/conf.d/02_ipsilon_vhost.conf
    mode: 0644
  notify:
    - restart_httpd

- name: Configuring https
  template:
    src: "{{ item }}.j2"
    dest: "/etc/httpd/conf.d/{{ item }}"
    mode: 0644
  notify:
    - restart_httpd
  with_items:
    - ssl-ipsilon-vhost.conf
  when: ipsilon_httpd_tls  
   
- import_role:
    name: httpd
    tasks_from: pki-tls
  vars:
    pki_hostname: "{{ ipsilon_httpd_hostname }}"
  notify:
    - restart_httpd
  tags:
    - tls
  when: ipsilon_httpd_tls

- name: Branding ipsilon with logo
  copy:
    src: centos_logo.png
    dest: "{{ item }}"
    mode: 0644
  with_items:
    - /usr/share/ipsilon/ui/img/brand-lg.png
    - /usr/share/ipsilon/ui/img/brand.png

- name: Distributing openidc genkey script
  copy:
    src: genkey.py
    dest: /var/lib/ipsilon/idp/genkey.py
    mode: 0755

- name: Ensuring backup user and jobs
  include_role:
    name: centos-backup
    tasks_from: client
  vars:
    - centos_role: ipsilon
    - role_backup_folders:
        - /var/lib/ipsilon 
  tags:
    - backup
